BASE_URL = "https://financialmodelingprep.com/api"
INDEX_PREFIX = "^"
SUPPORTED_INTERVALS = ["1min","5min","15min","30min","1hour","4hour"]
SUPPORTED_CATEGORIES = [
    'profile',
    'quote',
    'quote-short',
    'quotes',
    'search',
    'search-ticker',
    'income-statement',
    'balance-sheet-statement',
    'cash-flow-statement',
    'ratios',
    'enterprise-values',
    'key-metrics',
    'financial-growth',
    'rating',
    'discounted-cash-flow',
    'historical-discounted-cash-flow',
    'stock',
    'earning_calendar',
    'historical',
    'historical-chart',
    'historical-price-full',
    'stock-screener',
    'rss_feed',
    'sp500_constituent',
    'actives',
    'gainers',
    'losers',
    'market-hours',
    'sectors-performance',
    'financial-statement-symbol-lists',
    'historical/earning_calendar',
    'earning_call_transcript'
]
